name: consume_pipeline

pool: selfHosted

resources:
  pipelines:
  - pipeline: trigger
    project: tuttu
    source: root-pipelines/trigger
    trigger:    
      branches:
        include: 
        - main
      stages:
      - Production

stages:
  - stage: consume
    jobs:
      - job: consumejob
        steps:
          - script: echo "Hello, world!"

